[
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/883737673",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-883737673",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 883737673,
        "node_id": "IC_kwDOBWUGps40rMRJ",
        "user": {
            "login": "medAli-ai",
            "id": 42294664,
            "node_id": "MDQ6VXNlcjQyMjk0NjY0",
            "avatar_url": "https://avatars.githubusercontent.com/u/42294664?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/medAli-ai",
            "html_url": "https://github.com/medAli-ai",
            "followers_url": "https://api.github.com/users/medAli-ai/followers",
            "following_url": "https://api.github.com/users/medAli-ai/following{/other_user}",
            "gists_url": "https://api.github.com/users/medAli-ai/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/medAli-ai/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/medAli-ai/subscriptions",
            "organizations_url": "https://api.github.com/users/medAli-ai/orgs",
            "repos_url": "https://api.github.com/users/medAli-ai/repos",
            "events_url": "https://api.github.com/users/medAli-ai/events{/privacy}",
            "received_events_url": "https://api.github.com/users/medAli-ai/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-20T22:05:35Z",
        "updated_at": "2021-07-20T22:05:35Z",
        "author_association": "NONE",
        "body": "**Describe the bug**\r\nThe workaround mentioned by @aerdem4 isn't working anymore.\r\n\r\nThis workaround isn't working\r\n\r\n```\r\nindices = cudf.MultiIndex.from_product([data_df.to_pandas().index.levels[0], np.arange(0,600)], names = ['time_id', 'seconds_in_bucket'])\r\ndata_df = cudf.DataFrame().set_index(indices).join(data_df, how=\"left\").fillna(method='ffill').reset_index(drop=True)\r\n```\r\n\r\n[Kaggle notebook](https://www.kaggle.com/medali1992/optiver-train-dataset) mentioned above.\r\n\r\n**Environment overview (please complete the following information)**\r\nKaggle GPU Docker, RAPIDS 21.06",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/883737673/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/884254241",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-884254241",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 884254241,
        "node_id": "IC_kwDOBWUGps40tKYh",
        "user": {
            "login": "shwina",
            "id": 3190405,
            "node_id": "MDQ6VXNlcjMxOTA0MDU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3190405?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/shwina",
            "html_url": "https://github.com/shwina",
            "followers_url": "https://api.github.com/users/shwina/followers",
            "following_url": "https://api.github.com/users/shwina/following{/other_user}",
            "gists_url": "https://api.github.com/users/shwina/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/shwina/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shwina/subscriptions",
            "organizations_url": "https://api.github.com/users/shwina/orgs",
            "repos_url": "https://api.github.com/users/shwina/repos",
            "events_url": "https://api.github.com/users/shwina/events{/privacy}",
            "received_events_url": "https://api.github.com/users/shwina/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-21T14:53:49Z",
        "updated_at": "2021-07-21T14:53:49Z",
        "author_association": "CONTRIBUTOR",
        "body": "Thanks for reporting -- could you please point us to the `parquet` file being referenced in the code snippet above?",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/884254241/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/884277409",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-884277409",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 884277409,
        "node_id": "IC_kwDOBWUGps40tQCh",
        "user": {
            "login": "medAli-ai",
            "id": 42294664,
            "node_id": "MDQ6VXNlcjQyMjk0NjY0",
            "avatar_url": "https://avatars.githubusercontent.com/u/42294664?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/medAli-ai",
            "html_url": "https://github.com/medAli-ai",
            "followers_url": "https://api.github.com/users/medAli-ai/followers",
            "following_url": "https://api.github.com/users/medAli-ai/following{/other_user}",
            "gists_url": "https://api.github.com/users/medAli-ai/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/medAli-ai/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/medAli-ai/subscriptions",
            "organizations_url": "https://api.github.com/users/medAli-ai/orgs",
            "repos_url": "https://api.github.com/users/medAli-ai/repos",
            "events_url": "https://api.github.com/users/medAli-ai/events{/privacy}",
            "received_events_url": "https://api.github.com/users/medAli-ai/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-21T15:23:31Z",
        "updated_at": "2021-07-21T15:23:31Z",
        "author_association": "NONE",
        "body": "Hi @shwina ,\r\n\r\nYou just need to click on this [link](https://www.kaggle.com/medali1992/optiver-train-dataset/edit/run/68651140).\r\nThis is a kaggle notebook I created solely for this issue.\r\nYou need to create a kaggle account and you are good to go.\r\nTo enable **GPU** on kaggle notebook, just press the button **Accelerator** on the right below Environment preferences.\r\n\r\nAnd to use the notebook you need to press the **edit and copy** button on the right of the screen.\r\n\r\nHope the explanation is helpful.\r\n\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/884277409/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/884278892",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-884278892",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 884278892,
        "node_id": "IC_kwDOBWUGps40tQZs",
        "user": {
            "login": "medAli-ai",
            "id": 42294664,
            "node_id": "MDQ6VXNlcjQyMjk0NjY0",
            "avatar_url": "https://avatars.githubusercontent.com/u/42294664?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/medAli-ai",
            "html_url": "https://github.com/medAli-ai",
            "followers_url": "https://api.github.com/users/medAli-ai/followers",
            "following_url": "https://api.github.com/users/medAli-ai/following{/other_user}",
            "gists_url": "https://api.github.com/users/medAli-ai/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/medAli-ai/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/medAli-ai/subscriptions",
            "organizations_url": "https://api.github.com/users/medAli-ai/orgs",
            "repos_url": "https://api.github.com/users/medAli-ai/repos",
            "events_url": "https://api.github.com/users/medAli-ai/events{/privacy}",
            "received_events_url": "https://api.github.com/users/medAli-ai/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-21T15:25:30Z",
        "updated_at": "2021-07-21T15:25:30Z",
        "author_association": "NONE",
        "body": "Here is the [link](https://www.kaggle.com/c/optiver-realized-volatility-prediction/data) of the whole parquet dataset used in the competition.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/884278892/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/885720122",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-885720122",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 885720122,
        "node_id": "IC_kwDOBWUGps40ywQ6",
        "user": {
            "login": "beckernick",
            "id": 8457388,
            "node_id": "MDQ6VXNlcjg0NTczODg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8457388?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/beckernick",
            "html_url": "https://github.com/beckernick",
            "followers_url": "https://api.github.com/users/beckernick/followers",
            "following_url": "https://api.github.com/users/beckernick/following{/other_user}",
            "gists_url": "https://api.github.com/users/beckernick/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/beckernick/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/beckernick/subscriptions",
            "organizations_url": "https://api.github.com/users/beckernick/orgs",
            "repos_url": "https://api.github.com/users/beckernick/repos",
            "events_url": "https://api.github.com/users/beckernick/events{/privacy}",
            "received_events_url": "https://api.github.com/users/beckernick/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-23T15:29:58Z",
        "updated_at": "2021-07-23T15:29:58Z",
        "author_association": "MEMBER",
        "body": "Thanks for the additional context and links. Is there perhaps a direct link to the data, outside of Kaggle?",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/885720122/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/885724639",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-885724639",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 885724639,
        "node_id": "IC_kwDOBWUGps40yxXf",
        "user": {
            "login": "medAli-ai",
            "id": 42294664,
            "node_id": "MDQ6VXNlcjQyMjk0NjY0",
            "avatar_url": "https://avatars.githubusercontent.com/u/42294664?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/medAli-ai",
            "html_url": "https://github.com/medAli-ai",
            "followers_url": "https://api.github.com/users/medAli-ai/followers",
            "following_url": "https://api.github.com/users/medAli-ai/following{/other_user}",
            "gists_url": "https://api.github.com/users/medAli-ai/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/medAli-ai/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/medAli-ai/subscriptions",
            "organizations_url": "https://api.github.com/users/medAli-ai/orgs",
            "repos_url": "https://api.github.com/users/medAli-ai/repos",
            "events_url": "https://api.github.com/users/medAli-ai/events{/privacy}",
            "received_events_url": "https://api.github.com/users/medAli-ai/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-23T15:36:59Z",
        "updated_at": "2021-07-23T15:36:59Z",
        "author_association": "NONE",
        "body": "I can put the data into my google drive and share it with you if you want and besides you could download them from the kaggle website.\r\nJust create an account, sign in for the competition and you are good to go.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/885724639/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/885725805",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-885725805",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 885725805,
        "node_id": "IC_kwDOBWUGps40yxpt",
        "user": {
            "login": "medAli-ai",
            "id": 42294664,
            "node_id": "MDQ6VXNlcjQyMjk0NjY0",
            "avatar_url": "https://avatars.githubusercontent.com/u/42294664?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/medAli-ai",
            "html_url": "https://github.com/medAli-ai",
            "followers_url": "https://api.github.com/users/medAli-ai/followers",
            "following_url": "https://api.github.com/users/medAli-ai/following{/other_user}",
            "gists_url": "https://api.github.com/users/medAli-ai/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/medAli-ai/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/medAli-ai/subscriptions",
            "organizations_url": "https://api.github.com/users/medAli-ai/orgs",
            "repos_url": "https://api.github.com/users/medAli-ai/repos",
            "events_url": "https://api.github.com/users/medAli-ai/events{/privacy}",
            "received_events_url": "https://api.github.com/users/medAli-ai/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-23T15:38:55Z",
        "updated_at": "2021-07-23T15:38:55Z",
        "author_association": "NONE",
        "body": "Because you can't work with the data unless you accept the terms of the competiton",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/885725805/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/886798499",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-886798499",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 886798499,
        "node_id": "IC_kwDOBWUGps4023ij",
        "user": {
            "login": "shwina",
            "id": 3190405,
            "node_id": "MDQ6VXNlcjMxOTA0MDU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3190405?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/shwina",
            "html_url": "https://github.com/shwina",
            "followers_url": "https://api.github.com/users/shwina/followers",
            "following_url": "https://api.github.com/users/shwina/following{/other_user}",
            "gists_url": "https://api.github.com/users/shwina/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/shwina/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shwina/subscriptions",
            "organizations_url": "https://api.github.com/users/shwina/orgs",
            "repos_url": "https://api.github.com/users/shwina/repos",
            "events_url": "https://api.github.com/users/shwina/events{/privacy}",
            "received_events_url": "https://api.github.com/users/shwina/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-26T15:22:14Z",
        "updated_at": "2021-07-26T15:22:14Z",
        "author_association": "CONTRIBUTOR",
        "body": "Hi @medAli-ai - thanks again. Are you able to reproduce the issue on a smaller dataset, or better yet, independent of any particular dataset? That would greatly help us triage and resolve the problem.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/886798499/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/969317928",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-969317928",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 969317928,
        "node_id": "IC_kwDOBWUGps45xp4o",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "created_at": "2021-11-15T21:03:02Z",
        "updated_at": "2021-11-15T21:03:02Z",
        "author_association": "NONE",
        "body": "This issue has been labeled `inactive-90d` due to no recent activity in the past 90 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/969317928/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2108884453",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-2108884453",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 2108884453,
        "node_id": "IC_kwDOBWUGps59swXl",
        "user": {
            "login": "vyasr",
            "id": 1538165,
            "node_id": "MDQ6VXNlcjE1MzgxNjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1538165?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vyasr",
            "html_url": "https://github.com/vyasr",
            "followers_url": "https://api.github.com/users/vyasr/followers",
            "following_url": "https://api.github.com/users/vyasr/following{/other_user}",
            "gists_url": "https://api.github.com/users/vyasr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vyasr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vyasr/subscriptions",
            "organizations_url": "https://api.github.com/users/vyasr/orgs",
            "repos_url": "https://api.github.com/users/vyasr/repos",
            "events_url": "https://api.github.com/users/vyasr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vyasr/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-13T22:07:07Z",
        "updated_at": "2024-05-13T22:07:07Z",
        "author_association": "CONTRIBUTOR",
        "body": "This is not a MultiIndex issue, it's a data type issue.\r\n\r\nHere is a minimal example that reproduces the problem without requiring the Kaggle dataset:\r\n```\r\ndtype = \"int16\"\r\n# dtype = \"int64\" # We get the expected output if we uncomment this line\r\n\r\ndata_df = cudf.DataFrame({\r\n    \"time_id\": cudf.Series([5, 5, 5, 5, 5], dtype=dtype),\r\n    \"seconds_in_bucket\": cudf.Series([0, 1, 5, 6, 7], dtype=dtype)\r\n})\r\n\r\noffsets = data_df.groupby(\r\n    ['time_id'], as_index=False\r\n).agg(\r\n    {'seconds_in_bucket':'min'}\r\n).reset_index(drop=True)\r\noffsets.columns = ['time_id', 'offset']\r\ndata_df = cudf.merge(data_df, offsets, on = ['time_id'], how = 'left')\r\ndata_df = data_df.set_index(['time_id', 'seconds_in_bucket'])\r\ncolumns = [col for col in data_df.columns.values]\r\nmidx = cudf.MultiIndex.from_product(\r\n    [data_df.to_pandas().index.levels[0], np.arange(0,5)],\r\n    names=['time_id', 'seconds_in_bucket']\r\n)\r\ndata_df = data_df.reindex(midx, columns=columns).fillna(method='ffill').reset_index()\r\nprint(data_df['offset'])\r\n```\r\n\r\nNote that in the second line I don't observe the same issue with NaNs if I change the type. So what is happening?\r\n\r\nHere is a stripped down example that demonstrates the problem\r\n```\r\nimport cudf as pd\r\n# import pandas as pd  # This works\r\n\r\nstarting_dtype = \"int16\"\r\n# starting_dtype = \"int64\"  # This works\r\nidx = pd.Series([0, 1, 2, 3, 4], dtype=starting_dtype)\r\ndata_df = pd.DataFrame({\r\n    \"a\": idx,\r\n    \"b\": [0, 1, 5, 6, 7]\r\n}).set_index([\"a\"])\r\ndata_df = data_df.reindex(idx.astype(\"int64\")).fillna(method='ffill')\r\nassert data_df[\"b\"].isna().sum() == 0\r\n```\r\n\r\nThe issue is that that in the dataset in question, the index columns are int16 columns, whereas the MultiIndex used for reindexing contains a int64 columns by virtue of the `np.arange` call. The smaller example above demonstrates that directly. In order to match pandas here we should be upcasting to handle a merge correctly. Under the hood reindexing involves a merge, so I think that this issue ultimately boils down to something like https://github.com/rapidsai/cudf/issues/14594.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2108884453/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2108903682",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-2108903682",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 2108903682,
        "node_id": "IC_kwDOBWUGps59s1EC",
        "user": {
            "login": "vyasr",
            "id": 1538165,
            "node_id": "MDQ6VXNlcjE1MzgxNjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1538165?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vyasr",
            "html_url": "https://github.com/vyasr",
            "followers_url": "https://api.github.com/users/vyasr/followers",
            "following_url": "https://api.github.com/users/vyasr/following{/other_user}",
            "gists_url": "https://api.github.com/users/vyasr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vyasr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vyasr/subscriptions",
            "organizations_url": "https://api.github.com/users/vyasr/orgs",
            "repos_url": "https://api.github.com/users/vyasr/repos",
            "events_url": "https://api.github.com/users/vyasr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vyasr/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-13T22:23:22Z",
        "updated_at": "2024-05-13T22:23:22Z",
        "author_association": "CONTRIBUTOR",
        "body": "@wence- @mroeschke do you have any thoughts on if/how we should be addressing the above?",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2108903682/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2109763557",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-2109763557",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 2109763557,
        "node_id": "IC_kwDOBWUGps59wG_l",
        "user": {
            "login": "wence-",
            "id": 1126981,
            "node_id": "MDQ6VXNlcjExMjY5ODE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1126981?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/wence-",
            "html_url": "https://github.com/wence-",
            "followers_url": "https://api.github.com/users/wence-/followers",
            "following_url": "https://api.github.com/users/wence-/following{/other_user}",
            "gists_url": "https://api.github.com/users/wence-/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/wence-/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/wence-/subscriptions",
            "organizations_url": "https://api.github.com/users/wence-/orgs",
            "repos_url": "https://api.github.com/users/wence-/repos",
            "events_url": "https://api.github.com/users/wence-/events{/privacy}",
            "received_events_url": "https://api.github.com/users/wence-/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-14T09:48:31Z",
        "updated_at": "2024-05-14T09:48:31Z",
        "author_association": "CONTRIBUTOR",
        "body": "Merging already upcasts to a common dtype, so the problem is in reindexing, which has an explicit carve-out for whether the types in the left and right indices match:\r\n\r\n```\r\n# indexed_frame.py:_reindex\r\n            idx_dtype_match = (df.index.nlevels == index.nlevels) and all(\r\n                _is_same_dtype(left_dtype, right_dtype)\r\n                for left_dtype, right_dtype in zip(\r\n                    (col.dtype for col in df.index._data.columns),\r\n                    (col.dtype for col in index._data.columns),\r\n                )\r\n            )\r\n\r\n```\r\n\r\nI think a good place to start would be to consolidate all of the dtype-matching/promotion utilities in one place. One of the whack-a-mole issues here is that right now we haven't codified anywhere the dtype promotion and matching rules (either in code or docs), so all of these different places have _sui generis_ implementations that don't necessarily agree with each other.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2109763557/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2113621266",
        "html_url": "https://github.com/rapidsai/cudf/issues/8801#issuecomment-2113621266",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/8801",
        "id": 2113621266,
        "node_id": "IC_kwDOBWUGps59-00S",
        "user": {
            "login": "vyasr",
            "id": 1538165,
            "node_id": "MDQ6VXNlcjE1MzgxNjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1538165?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vyasr",
            "html_url": "https://github.com/vyasr",
            "followers_url": "https://api.github.com/users/vyasr/followers",
            "following_url": "https://api.github.com/users/vyasr/following{/other_user}",
            "gists_url": "https://api.github.com/users/vyasr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vyasr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vyasr/subscriptions",
            "organizations_url": "https://api.github.com/users/vyasr/orgs",
            "repos_url": "https://api.github.com/users/vyasr/repos",
            "events_url": "https://api.github.com/users/vyasr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vyasr/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-15T23:02:48Z",
        "updated_at": "2024-05-15T23:02:48Z",
        "author_association": "CONTRIBUTOR",
        "body": "Good catch, thanks for pointing that out. We could definitely get a lot of mileage out of standardizing more of these kinds of internal helper logic functions.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2113621266/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]