{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/12791",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/12791/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/12791/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/12791/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/12791",
    "id": 1587943984,
    "node_id": "I_kwDOBWUGps5ephow",
    "number": 12791,
    "title": "[BUG] cudf.cut does not accept sequence of scalars",
    "user": {
        "login": "mattf",
        "id": 112653,
        "node_id": "MDQ6VXNlcjExMjY1Mw==",
        "avatar_url": "https://avatars.githubusercontent.com/u/112653?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mattf",
        "html_url": "https://github.com/mattf",
        "followers_url": "https://api.github.com/users/mattf/followers",
        "following_url": "https://api.github.com/users/mattf/following{/other_user}",
        "gists_url": "https://api.github.com/users/mattf/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mattf/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mattf/subscriptions",
        "organizations_url": "https://api.github.com/users/mattf/orgs",
        "repos_url": "https://api.github.com/users/mattf/repos",
        "events_url": "https://api.github.com/users/mattf/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mattf/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 1013987352,
            "node_id": "MDU6TGFiZWwxMDEzOTg3MzUy",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/0%20-%20Backlog",
            "name": "0 - Backlog",
            "color": "d4c5f9",
            "default": false,
            "description": "In queue waiting for assignment"
        },
        {
            "id": 1139741213,
            "node_id": "MDU6TGFiZWwxMTM5NzQxMjEz",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/Python",
            "name": "Python",
            "color": "1d76db",
            "default": false,
            "description": "Affects Python cuDF API."
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2023-02-16T15:52:39Z",
    "updated_at": "2023-06-06T05:04:16Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nworking with `import cudf as pd`\r\n\r\n**Steps/Code to reproduce bug**\r\n```\r\nIn [1]: import cudf as pd\r\n\r\nIn [2]: pd.__version__\r\nOut[2]: '23.02.00'\r\n\r\nIn [3]: import numpy as np\r\n\r\nIn [4]: df = pd.DataFrame({'a': range(100)})\r\n\r\nIn [5]: pd.cut(df.a, bins=np.linspace(0, 100, num=6))\r\n---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\n<ipython-input-5-1d55c0477181> in <module>\r\n----> 1 pd.cut(df.a, bins=np.linspace(0, 100, num=6))\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/cut.py in cut(x, bins, right, labels, retbins, precision, include_lowest, duplicates, ordered)\r\n    168                 mn = min(x)\r\n    169                 mx = max(x)\r\n--> 170             bins = np.linspace(mn, mx, bins + 1, endpoint=True)\r\n    171             adj = (mx - mn) * 0.001\r\n    172             if right:\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/numpy/core/overrides.py in linspace(*args, **kwargs)\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)\r\n    118 \r\n    119     \"\"\"\r\n--> 120     num = operator.index(num)\r\n    121     if num < 0:\r\n    122         raise ValueError(\"Number of samples, %s, must be non-negative.\" % num)\r\n\r\nTypeError: only integer scalar arrays can be converted to a scalar index\r\n\r\nIn [6]: import pandas\r\n\r\nIn [7]: pandas.cut(df.to_pandas().a, bins=np.linspace(0, 100, num=6))\r\nOut[7]: \r\n0               NaN\r\n1       (0.0, 20.0]\r\n2       (0.0, 20.0]\r\n3       (0.0, 20.0]\r\n4       (0.0, 20.0]\r\n          ...      \r\n95    (80.0, 100.0]\r\n96    (80.0, 100.0]\r\n97    (80.0, 100.0]\r\n98    (80.0, 100.0]\r\n99    (80.0, 100.0]\r\nName: a, Length: 100, dtype: category\r\nCategories (5, interval[float64, right]): [(0.0, 20.0] < (20.0, 40.0] < (40.0, 60.0] <\r\n                                           (60.0, 80.0] < (80.0, 100.0]]\r\n```\r\n\r\n**Additional context**\r\nhttps://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.cut.html\r\n![image](https://user-images.githubusercontent.com/112653/219417718-173071c7-55c3-4bc0-9b4f-425bd0b0ee81.png)\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/12791/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/12791/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}