{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/13731",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/13731/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/13731/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/13731/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/13731",
    "id": 1816443163,
    "node_id": "I_kwDOBWUGps5sRLkb",
    "number": 13731,
    "title": "[BUG] `TypeError` when broadcasting `Series` to `DataFrame` with non-numerical columns",
    "user": {
        "login": "rjzamora",
        "id": 20461013,
        "node_id": "MDQ6VXNlcjIwNDYxMDEz",
        "avatar_url": "https://avatars.githubusercontent.com/u/20461013?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rjzamora",
        "html_url": "https://github.com/rjzamora",
        "followers_url": "https://api.github.com/users/rjzamora/followers",
        "following_url": "https://api.github.com/users/rjzamora/following{/other_user}",
        "gists_url": "https://api.github.com/users/rjzamora/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rjzamora/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rjzamora/subscriptions",
        "organizations_url": "https://api.github.com/users/rjzamora/orgs",
        "repos_url": "https://api.github.com/users/rjzamora/repos",
        "events_url": "https://api.github.com/users/rjzamora/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rjzamora/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 1013987352,
            "node_id": "MDU6TGFiZWwxMDEzOTg3MzUy",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/0%20-%20Backlog",
            "name": "0 - Backlog",
            "color": "d4c5f9",
            "default": false,
            "description": "In queue waiting for assignment"
        },
        {
            "id": 1139741213,
            "node_id": "MDU6TGFiZWwxMTM5NzQxMjEz",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/Python",
            "name": "Python",
            "color": "1d76db",
            "default": false,
            "description": "Affects Python cuDF API."
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": {
        "url": "https://api.github.com/repos/rapidsai/cudf/milestones/5",
        "html_url": "https://github.com/rapidsai/cudf/milestone/5",
        "labels_url": "https://api.github.com/repos/rapidsai/cudf/milestones/5/labels",
        "id": 6955120,
        "node_id": "MI_kwDOBWUGps4AaiBw",
        "number": 5,
        "title": "Pandas API Alignment and Coverage",
        "description": "",
        "creator": {
            "login": "beckernick",
            "id": 8457388,
            "node_id": "MDQ6VXNlcjg0NTczODg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8457388?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/beckernick",
            "html_url": "https://github.com/beckernick",
            "followers_url": "https://api.github.com/users/beckernick/followers",
            "following_url": "https://api.github.com/users/beckernick/following{/other_user}",
            "gists_url": "https://api.github.com/users/beckernick/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/beckernick/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/beckernick/subscriptions",
            "organizations_url": "https://api.github.com/users/beckernick/orgs",
            "repos_url": "https://api.github.com/users/beckernick/repos",
            "events_url": "https://api.github.com/users/beckernick/events{/privacy}",
            "received_events_url": "https://api.github.com/users/beckernick/received_events",
            "type": "User",
            "site_admin": false
        },
        "open_issues": 114,
        "closed_issues": 124,
        "state": "open",
        "created_at": "2021-07-16T17:49:59Z",
        "updated_at": "2024-06-03T17:45:11Z",
        "due_on": null,
        "closed_at": null
    },
    "comments": 1,
    "created_at": "2023-07-21T22:25:52Z",
    "updated_at": "2024-05-16T05:12:34Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nI am getting a `TypeError` when I try to subtract a `cudf.Series` (`s`) from a `cudf.Dataframe` (`df`) having non-numerical columns, even when `s` only contains elements that correspond to the numerical columns of `df`. Note that it is not an issue when `s` leaves out columns of `df`, unless those columns are numerical.\r\n\r\n**Steps/Code to reproduce bug**\r\n```python\r\nIn [1]: import cudf\r\nIn [2]: df = cudf.DataFrame({\"a\": [\"dog\"] * 10, \"b\": range(10)})\r\nIn [3]: s = df.mean(numeric_only=True)\r\nIn [4]: df - s\r\n```\r\n```\r\n---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\nCell In[4], line 1\r\n----> 1 df - s\r\n\r\nFile /datasets/rzamora/miniconda3/envs/cudf_pandas_2/lib/python3.10/site-packages/cudf/core/mixins/mixin_factory.py:11, in _partialmethod.<locals>.wrapper(self, *args2, **kwargs2)\r\n     10 def wrapper(self, *args2, **kwargs2):\r\n---> 11     return method(self, *args1, *args2, **kwargs1, **kwargs2)\r\n\r\nFile /datasets/rzamora/miniconda3/envs/cudf_pandas_2/lib/python3.10/site-packages/cudf/core/indexed_frame.py:3475, in IndexedFrame._binaryop(self, other, op, fill_value, can_reindex, *args, **kwargs)\r\n   3471 if operands is NotImplemented:\r\n   3472     return NotImplemented\r\n   3474 return self._from_data(\r\n-> 3475     ColumnAccessor(type(self)._colwise_binop(operands, op)),\r\n   3476     index=out_index,\r\n   3477 )\r\n\r\nFile /datasets/rzamora/miniconda3/envs/cudf_pandas_2/lib/python3.10/site-packages/nvtx/nvtx.py:101, in annotate.__call__.<locals>.inner(*args, **kwargs)\r\n     98 @wraps(func)\r\n     99 def inner(*args, **kwargs):\r\n    100     libnvtx_push_range(self.attributes, self.domain.handle)\r\n--> 101     result = func(*args, **kwargs)\r\n    102     libnvtx_pop_range(self.domain.handle)\r\n    103     return result\r\n\r\nFile /datasets/rzamora/miniconda3/envs/cudf_pandas_2/lib/python3.10/site-packages/cudf/core/frame.py:1761, in Frame._colwise_binop(cls, operands, fn)\r\n   1753         assert False, \"At least one operand must be a column.\"\r\n   1755 # TODO: Disable logical and binary operators between columns that\r\n   1756 # are not numerical using the new binops mixin.\r\n   1758 outcol = (\r\n   1759     getattr(operator, fn)(right_column, left_column)\r\n   1760     if reflect\r\n-> 1761     else getattr(operator, fn)(left_column, right_column)\r\n   1762 )\r\n   1764 if output_mask is not None:\r\n   1765     outcol = outcol.set_mask(output_mask)\r\n\r\nTypeError: unsupported operand type(s) for -: 'StringColumn' and 'NoneType'\r\n```\r\n\r\nFor `pandas`, I get the following output:\r\n\r\n```\r\n     a    b\r\n0  NaN -4.5\r\n1  NaN -3.5\r\n2  NaN -2.5\r\n3  NaN -1.5\r\n4  NaN -0.5\r\n5  NaN  0.5\r\n6  NaN  1.5\r\n7  NaN  2.5\r\n8  NaN  3.5\r\n9  NaN  4.5\r\n```\r\n\r\n**Expected behavior**\r\nI expect the same behavior as pandas. That is, when broadcasting a `Series` to the columns of a `DataFrame` for a binop, missing columns in the `Series`' index should result in the corresponding column having all null values in the output. This seems to work fine in `cudf`, unless the missing column is non-numerical.",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/13731/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/13731/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}