{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/15820",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/15820/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/15820/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/15820/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/15820",
    "id": 2311285467,
    "node_id": "I_kwDOBWUGps6Jw2rb",
    "number": 15820,
    "title": "[BUG] `cudf.read_json` does not raise an exception with invalid data when `lines=True` and `engine='cudf'`",
    "user": {
        "login": "dagardner-nv",
        "id": 96306125,
        "node_id": "U_kgDOBb2DzQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/96306125?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dagardner-nv",
        "html_url": "https://github.com/dagardner-nv",
        "followers_url": "https://api.github.com/users/dagardner-nv/followers",
        "following_url": "https://api.github.com/users/dagardner-nv/following{/other_user}",
        "gists_url": "https://api.github.com/users/dagardner-nv/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dagardner-nv/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dagardner-nv/subscriptions",
        "organizations_url": "https://api.github.com/users/dagardner-nv/orgs",
        "repos_url": "https://api.github.com/users/dagardner-nv/repos",
        "events_url": "https://api.github.com/users/dagardner-nv/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dagardner-nv/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-05-22T19:04:58Z",
    "updated_at": "2024-05-22T19:04:58Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\n`cudf.read_json` doesn't raise an exception when parsing invalid json when `lines=True` and `engine='cudf'`. Instead it returns a single row DF with an empty string value.\r\n\r\nSetting `lines=False` raises a `RuntimeError` (should be a `ValueError`).\r\nAlternately setting `engine='pandas'` raises a `ValueError`.\r\n\r\n**Steps/Code to reproduce bug**\r\n```python\r\nfrom io import StringIO\r\n\r\nimport cudf\r\n\r\nprint(cudf.__version__)\r\ninvalid_payload = '{\"not_valid\":\"json'\r\n\r\n# Produces a single row DF\r\nprint(\"Testing lines=True, engine=cudf\")\r\nprint(cudf.read_json(StringIO(invalid_payload), lines=True, engine='cudf'))\r\n\r\n\r\n# Works as expected\r\nprint(\"Testing lines=False, engine=cudf\")\r\ntry: \r\n    cudf.read_json(StringIO(invalid_payload), lines=False, engine='cudf')\r\nexcept Exception as e:\r\n    print(e)\r\n\r\n# Works as expected\r\nprint(\"Testing lines=True, engine=pandas\")\r\ntry:\r\n    cudf.read_json(StringIO(invalid_payload), lines=True, engine='pandas')\r\nexcept Exception as e:\r\n    print(e)\r\n```\r\n\r\n**Expected behavior**\r\nA raised `ValueError`, although any exception is better than \r\n\r\n**Environment overview (please complete the following information)**\r\n - Environment location: [Bare-metal]\r\n - Method of cuDF install: [conda]\r\n\r\nObserved in versions 24.04.01 and 24.02.02",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/15820/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/15820/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}