{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/12790",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/12790/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/12790/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/12790/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/12790",
    "id": 1587919845,
    "node_id": "I_kwDOBWUGps5epbvl",
    "number": 12790,
    "title": "[BUG] cudf.cut fails on example from documentation",
    "user": {
        "login": "mattf",
        "id": 112653,
        "node_id": "MDQ6VXNlcjExMjY1Mw==",
        "avatar_url": "https://avatars.githubusercontent.com/u/112653?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mattf",
        "html_url": "https://github.com/mattf",
        "followers_url": "https://api.github.com/users/mattf/followers",
        "following_url": "https://api.github.com/users/mattf/following{/other_user}",
        "gists_url": "https://api.github.com/users/mattf/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mattf/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mattf/subscriptions",
        "organizations_url": "https://api.github.com/users/mattf/orgs",
        "repos_url": "https://api.github.com/users/mattf/repos",
        "events_url": "https://api.github.com/users/mattf/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mattf/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 1013987352,
            "node_id": "MDU6TGFiZWwxMDEzOTg3MzUy",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/0%20-%20Backlog",
            "name": "0 - Backlog",
            "color": "d4c5f9",
            "default": false,
            "description": "In queue waiting for assignment"
        },
        {
            "id": 1139741213,
            "node_id": "MDU6TGFiZWwxMTM5NzQxMjEz",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/Python",
            "name": "Python",
            "color": "1d76db",
            "default": false,
            "description": "Affects Python cuDF API."
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2023-02-16T15:38:22Z",
    "updated_at": "2023-06-05T19:02:02Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nlast example in https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.cut.html\r\n\r\n**Steps/Code to reproduce bug**\r\n```\r\nIn [1]: import cudf\r\n\r\nIn [2]: cudf.__version__\r\nOut[2]: '23.02.00'\r\n\r\nIn [3]: import numpy as np\r\n\r\nIn [4]: s = cudf.Series(np.array([2, 4, 6, 8, 10]), index=['a', 'b', 'c', 'd', 'e'])\r\n   ...: cudf.cut(s, 3)\r\nOut[4]: ---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)\r\n    700                 type_pprinters=self.type_printers,\r\n    701                 deferred_pprinters=self.deferred_printers)\r\n--> 702             printer.pretty(obj)\r\n    703             printer.flush()\r\n    704             return stream.getvalue()\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)\r\n    392                         if cls is not object \\\r\n    393                                 and callable(cls.__dict__.get('__repr__')):\r\n--> 394                             return _repr_pprint(obj, self, cycle)\r\n    395 \r\n    396             return _default_pprint(obj, self, cycle)\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)\r\n    698     \"\"\"A pprint that just redirects to the normal repr function.\"\"\"\r\n    699     # Find newlines and replace them with p.break_()\r\n--> 700     output = repr(obj)\r\n    701     lines = output.splitlines()\r\n    702     with p.group():\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py in __repr__(self)\r\n   1323                 )\r\n   1324             else:\r\n-> 1325                 pd_series = preprocess.to_pandas()\r\n   1326             output = pd_series.to_string(\r\n   1327                 name=self.name,\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/contextlib.py in inner(*args, **kwds)\r\n     73         def inner(*args, **kwds):\r\n     74             with self._recreate_cm():\r\n---> 75                 return func(*args, **kwds)\r\n     76         return inner\r\n     77 \r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py in to_pandas(self, index, nullable, **kwargs)\r\n   1900         if index is True:\r\n   1901             index = self.index.to_pandas()\r\n-> 1902         s = self._column.to_pandas(index=index, nullable=nullable)\r\n   1903         s.name = self.name\r\n   1904         return s\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/categorical.py in to_pandas(self, index, **kwargs)\r\n    913         else:\r\n    914             categories = col.categories.dropna(drop_nan=True).to_pandas()\r\n--> 915         data = pd.Categorical.from_codes(\r\n    916             codes, categories=categories, ordered=col.ordered\r\n    917         )\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/arrays/categorical.py in from_codes(cls, codes, categories, ordered, dtype)\r\n    685         Categories (2, object): ['a' < 'b']\r\n    686         \"\"\"\r\n--> 687         dtype = CategoricalDtype._from_values_or_dtype(\r\n    688             categories=categories, ordered=ordered, dtype=dtype\r\n    689         )\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py in _from_values_or_dtype(cls, values, categories, ordered, dtype)\r\n    297             # Note: This could potentially have categories=None and\r\n    298             # ordered=None.\r\n--> 299             dtype = CategoricalDtype(categories, ordered)\r\n    300 \r\n    301         return cast(CategoricalDtype, dtype)\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py in __init__(self, categories, ordered)\r\n    184 \r\n    185     def __init__(self, categories=None, ordered: Ordered = False) -> None:\r\n--> 186         self._finalize(categories, ordered, fastpath=False)\r\n    187 \r\n    188     @classmethod\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py in _finalize(self, categories, ordered, fastpath)\r\n    338 \r\n    339         if categories is not None:\r\n--> 340             categories = self.validate_categories(categories, fastpath=fastpath)\r\n    341 \r\n    342         self._categories = categories\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py in validate_categories(categories, fastpath)\r\n    534                 raise ValueError(\"Categorical categories cannot be null\")\r\n    535 \r\n--> 536             if not categories.is_unique:\r\n    537                 raise ValueError(\"Categorical categories must be unique\")\r\n    538 \r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/_libs/properties.pyx in pandas._libs.properties.CachedProperty.__get__()\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/core/indexes/base.py in is_unique(self)\r\n   2384         Return if the index has unique values.\r\n   2385         \"\"\"\r\n-> 2386         return self._engine.is_unique\r\n   2387 \r\n   2388     @final\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.is_unique.__get__()\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine._do_unique_check()\r\n\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine._ensure_mapping_populated()\r\n\r\npandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.map_locations()\r\n\r\nTypeError: unhashable type: 'dict'\r\n```",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/12790/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/12790/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}